### ISSUE TITLE
main fails to compile with SnakeYAML 2.x

### ISSUE THREAD

**Issue by dogancanbakir** [projectdiscovery/nuclei-burp-plugin#133]
`main` does not compile. `mvn test` fails with two errors:

```
NucleiModelConstructor.java:[39] error: no suitable constructor found for Constructor(no arguments)
OrderedRepresenter.java:[44,52] error: constructor Representer in class Representer cannot be applied to given types
```

SnakeYAML 2.x removed the no-arg `Constructor()` and `Representer()` constructors, but #128 bumped 1.33 to 2.5 without updating the two subclasses.

Reported in #131 as "right-click Generate template not working in Burp Suite 2025.11.x", which fits: recent Burp releases put SnakeYAML 2.x on the classpath ahead of the 1.33 bundled in the released jar, so the 1.33-compiled call sites hit `NoSuchMethodError` at runtime.
